### ISSUE TITLE
popins place-refalign: Location reference not found in contig file

### ISSUE THREAD

**Issue by alexandervogel** [bkehr/popins#10] opened 2019-05-22 07:44 UTC
When running the place-refalign subcommand I get the following error:

> ERROR: Location references a contig that was not found in contig file: Chr_02

Chr_02 is part of the reference genome used for the alignment but not part of supercontigs.fa. I do see quite a few (42 / 57066) of reference contig identifiers in the merged locations.txt file. Filtering out lines refering to reference contigs in the merged locations.txt file led to the pipeline failing in a later step.
Could it be related to a repetitive element that is already part of the genome on a other chromosome?

Versions
bwa: 0.7.17-r1188
samtools: 1.9
seqan: 2.2.0

It would be great if you could provide some feedback. Thanks!

**Comment by bkehr** [comment] 2019-05-22 11:55
I haven't seen this error message before. Can you send me the exact commands with all options you used for running popins contigmap? And can you confirm that Chr_02 is part of the reference genome specified with the -r option in the contig map command?

**Comment by alexandervogel** [comment] 2019-05-22 12:52
Thanks for the feedback. I can confirm that Chr_02 is part of the reference genome. 
```bash
grep '^>Chr_02' ./ref/genome.fasta
>Chr_02 
```
I ran the contigmap step in parallel on a cluster as follows (after indexing the supercontigs.fa seperately):

```bash
/path/to/popins contigmap \
-p ./samples/ \
-t 8 \
-r ./ref/genome.fasta \
Sample_001
```

Checking the log indicates that the step finished for my test subset of five samles:
```bash
[PopIns 2019-05-22 09:16:07] popins contigmap finished in 33 seconds.
[PopIns 2019-05-22 09:16:19] popins contigmap finished in 46 seconds.
[PopIns 2019-05-22 09:16:21] popins contigmap finished in 48 seconds.
[PopIns 2019-05-22 09:16:23] popins contigmap finished in 49 seconds.
[PopIns 2019-05-22 09:17:13] popins contigmap finished in 99 seconds.
```

The complete output of the place-refalign step is as follows:

```bash
[PopIns 2019-05-22 09:17:31] Listing locations files.
[PopIns 2019-05-22 09:17:32] Merging 5 locations files.
[PopIns 2019-05-22 09:17:32] Reading locations from locations.txt
[PopIns 2019-05-22 09:17:32] Loaded 18731 locations that pass filters.
[PopIns 2019-05-22 09:17:32] Reading contig sequences from supercontigs.fa
[PopIns 2019-05-22 09:17:32] Loaded 12726 contig sequences.
[PopIns 2019-05-22 09:17:33] Aligning contigs to reference
ERROR: Location references a contig that was not found in contig file: Chr_02
```

Maybe the output of the merged insertions.txt file could be of help (only selected some relevant lines here).

```bash 
$cat locations.txt | awk '$3 ~ /^Chr/' | head -n 5
Chr_09:7014854-7014953  +       Chr_02  +       1       0.5     Sample_001:1
Chr_07:28413734-28413844        -       Chr_04  +       20      0.740741        Sample_001:6,Sample_002:5,Sample_003:5,Sample_004:3,Sample_005:1
Chr_11:15550127-15550197        +       Chr_04  +       1       0.037037        Sample_001:1
Chr_07:31018028-31018128        -       Chr_05  -       1       0.333333        Sample_001:1
Chr_10:11032462-11032514        -       Chr_05  -       1       0.333333        Sample_001:1
```

**Comment by bkehr** [comment] 2019-05-23 10:00
Thanks, the lines from the merged ``locations.txt`` are helpful and confirm that the error occurs somewhere earlier. The third columns is not supposed to contain any chromosome names, only contig names. I guess that you see the same in ``samples/Sample_001/locations.txt``?

Your contigmap command seems alright. Since I am still clueless what causes the error, can you doublecheck that ``Chr_02`` does not occur in the ``supercontigs.fa`` and send me all commands you used up to the contig mapping?

It would be easiest if I could reproduce the error here, which is probably not possible as I would need access to your data. To trace it, could you run

```
samtools view samples/Sample_001/non_ref_new.bam | awk '$3 == "Chr_09" && $7 == "Chr_02"' | head -n 1
```

and find all records of the resulting read in ``samples/Sample_001/non_ref.bam``?

**Comment by bkehr** [comment] 2020-01-03 12:09
I am closing this issue as I did not receive a reply in more than 6 months. Please reopen in case the problem persists.

**Closed as completed by bkehr** 2020-01-03 12:09 UTC

**Comment by marivelasque** [comment] 2020-05-20 03:19
I had the same problem and I think I found the source. When running  'popins place-refalign -p result_location/sample1' it tries to locate _locations_unplaced.txt_ at _result_location/sample1/sample1_. I don't have two "sample1" folders.
