### ISSUE TITLE
explanation vcf

### ISSUE THREAD

**Issue by Jordi-V** [bkehr/popins#8] opened 2019-03-26 16:19 UTC
Dear Brite,

I've questions about the info provided by vcf of popins.

I did all steps, and what does it means, COMPONENT??
2       236824003       2:236824003:FP  C       ]Sample621.NODE_94230_length_132_cov_3.181818r:102]C      .       .       NOANCHOR        GT:PL   0/0:0,128,255
2       237068838       2:237068838:FP  G       ]Sample838.NODE_55839_length_105_cov_2.000000r:85]G       .       .       NOANCHOR        GT:PL   0/0:0,192,255
2       237235459       2:237235459:FP  G       G[Sample717.NODE_82940_length_102_cov_2.921569f:67[       .       .       AR=3;AS=0.3;GS=1        GT:PL   0/0:0,109,255
2       237313565       2:237313565:FP  A       A[Sample.NODE_89256_length_104_cov_2.000000r:42[       .       .       AR=2;AS=1;GS=1  GT:PL   0/0:0,95,255
2       237451558       2:237451558:FP  A       ]COMPONENT_16411_a_length_445_size_207f:320]A   .       .       AR=1351;AS=0.995578;GS=2        GT:PL   0/1:255,0,255
2       237451559       2:237451559:FP  T       T[COMPONENT_16411_a_length_445_size_207f:76[    .       .       AR=1030;AS=0.995169;GS=5        GT:PL   0/1:255,0,255

And I dont know what does it mean AR, AS, GS... The NONANCHOR are variants which may be are false positives right?

Finally I ran several samples  with popins, and I merged like you mention in github, but I found most of the times the same variant and genotype between different samples, it means its really common found 70% of samples with the same genotype and variant... So I want to know if it is normal...

Thanks for your help and time

Jordi

**Comment by bkehr** [comment] 2019-03-26 16:28
For your questions regarding the VCF format, please see this previous reply: https://github.com/bkehr/popins/issues/3#issuecomment-298373086

I am not sure I understand your last question. Are you saying that you observe all variants in 70% of the samples? This is something I would not expect.

**Comment by Jordi-V** [comment] 2019-03-26 17:06
ok thanks!

Yes I'm looking randomly some variants from outputs of popins randomly, and in general I found several samples which share the same genotype and position of variant... I follow exactly the steps from github. It means:
popins assemble -s sample1 -t 24 -mp sample1.bam -p ./ sample1.bam
popins assemble -s sample2 -t 24 -mp sample2.bam -p ./ sample2.bam
.
.
.
popins merge -p ./ -c supercontigs.fa
popins contigmap -r genome_women.fa -t 48 -p ./ -c supercontigs.fa sample1
popins contigmap -r genome_women.fa -t 48 -p ./ -c supercontigs.fa sample2
.
.
.
popins place-refalign -r genome.fa  --readLength 150  -p ./  -c supercontigs.fa
popins place-splitalign -r genome_women.fa -p ./ --readLength 150 -c supercontigs.fa sample1
popins place-splitalign -r genome_women.fa -p ./ --readLength 150 -c supercontigs.fa sample2
.
.
.
popins place-finish -r genome.fa -p ./  -i insertions.vcf
popins genotype -r genome_women.fa -p ./ -i insertions.vcf -c supercontigs.fa sample1
popins genotype -r genome_women.fa -p ./ -i insertions.vcf -c supercontigs.fa sample2
.
.
.

So I think that the process is correct, I ran 785 samples and i look the insertions combining all variants between them. So If I found common variants between samples in high frequency, do you think that I'm wrong? I do something wrong during the process? 

Thanks for your help

**Comment by Jordi-V** [comment] 2019-03-26 17:08
For All variants I dont know, but some of them yes... After reading the vcf I hope that the frequency of insertions which have COMPONENT could be higher than others right?

Thanks

**Comment by bkehr** [comment] 2019-03-26 17:18
The process looks correct to me (assuming that ``genome.fa`` vs. ``genome_women.fa`` is just a typo).

Seeing the exact same set of variants in two samples is unexpected. If this is the case, then I recommend double checking all input and intermediate files to differ between samples (e.g. by checking their size). If you see only some variants shared between samples, this is biology.

**Comment by Jordi-V** [comment] 2019-03-26 18:17
Hi,
this is an example... Each line is one sample different:

       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,253
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,122
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,120
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,87
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/0:0,84,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/0:0,100,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,234
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/0:0,88,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,240
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,85
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,229
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,167
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,158
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:186,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:255,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/1:44,0,255
3       31881398        3:31881398:FP   A       A[CWGS066.NODE_6385_length_109_cov_2.155963f:111[       .       .       AR=51;AS=0.447368;GS=2  GT:PL   0/0:0,127,255

for me is surprisingly, but can be...

Thanks

**Comment by Jordi-V** [comment] 2019-03-26 18:18
The vast majority of samples are heterozygous in exception of 2, and all values are more and less exactly the same...

**Comment by bkehr** [comment] 2019-03-27 10:29
The (PHRED-scaled) genotype likelihoods are often the same since PopIns caps them at 255. This is common practise in many other tools, too.

I agree that from a population genetics point of view, it is unexpected to have such a distribution of genotypes. PopIns has high genotyping accuracy for "well-behaved" variants. However, in complex genomic regions, e.g. involving repeats, short read data is often not sufficient to resolve the complexity and misleads analysis programs. (Please see the [supplement of our Nature Genetics paper](https://media.nature.com/full/nature-assets/ng/journal/v49/n4/extref/ng.3801-S1.pdf), pages 9-11, to understand the details of how PopIns computes genotype likelihoods.) Because of this limitation, we used a filtering procedure of the PopIns output in the analysis of Icelandic non-reference sequence variants.

I will close this issue as this is not a bug of PopIns but expected behaviour.

**Closed as completed by bkehr** 2019-03-27 10:29 UTC
